In [2]:
path_pattern = "/workspaces/mads-siads-699-winter-2026-capstone/notebooks/data/source_data/initial_dataset/*.parquet"

In [5]:
import polars as pl
import glob

all_files = sorted(glob.glob(path_pattern))
first_five = all_files[:10]
if first_five:
    df = pl.read_parquet(first_five)
    print(f"Loaded {len(first_five)} files.")

Loaded 10 files.

In [8]:
df.shape

(26055035, 8)

In [7]:
df.head(30)

shape: (30, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ SnapshotAt ┆ package_na ┆ package_ve ┆ package_p ┆ dep_name  ┆ dep_versi ┆ MinimumDe ┆ github_re │
│ ---        ┆ me         ┆ rsion      ┆ ublished_ ┆ ---       ┆ on        ┆ pth       ┆ po        │
│ datetime[μ ┆ ---        ┆ ---        ┆ at        ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆ str        ┆ str        ┆ ---       ┆           ┆ str       ┆ i64       ┆ str       │
│            ┆            ┆            ┆ datetime[ ┆           ┆           ┆           ┆           │
│            ┆            ┆            ┆ μs]       ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ certifi   ┆ 2022.12.7 ┆ 3         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆           ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ charset-n ┆ 3.1.0     ┆ 3         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆ ormalizer ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ django-db ┆ 0.1.7     ┆ 1         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆ conn-retr ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆ y         ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ hvac      ┆ 1.1.0     ┆ 1         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆           ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ idna      ┆ 3.4.0     ┆ 3         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆           ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2023-04-10 ┆ 2captcha-p ┆ 1.2.0      ┆ null      ┆ urllib3   ┆ 1.26.15   ┆ 2         ┆ 2captcha/ │
│ 21:01:49.2 ┆ ython      ┆            ┆           ┆           ┆           ┆           ┆ 2captcha- │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ python    │
│ 2023-04-10 ┆ 2ppy       ┆ 0.4.0      ┆ null      ┆ jpype1    ┆ 1.3.0     ┆ 1         ┆ tuprolog/ │
│ 21:01:49.2 ┆            ┆            ┆           ┆           ┆           ┆           ┆ 2ppy      │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 2023-04-10 ┆ a-cv-imwri ┆ 0.11.0     ┆ null      ┆ certifi   ┆ 2022.12.7 ┆ 2         ┆ hansalema │
│ 21:01:49.2 ┆ te-imread- ┆            ┆           ┆           ┆           ┆           ┆ os/a_cv_i │
│ 19309      ┆ plus       ┆            ┆           ┆           ┆           ┆           ┆ mwrite_im │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ rea…      │
│ 2023-04-10 ┆ a-cv-imwri ┆ 0.11.0     ┆ null      ┆ charset-n ┆ 3.1.0     ┆ 2         ┆ hansalema │
│ 21:01:49.2 ┆ te-imread- ┆            ┆           ┆ ormalizer ┆           ┆           ┆ os/a_cv_i │
│ 19309      ┆ plus       ┆            ┆           ┆           ┆           ┆           ┆ mwrite_im │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ rea…      │
│ 2023-04-10 ┆ a-cv-imwri ┆ 0.11.0     ┆ null      ┆ idna      ┆ 3.4.0     ┆ 2         ┆ hansalema │
│ 21:01:49.2 ┆ te-imread- ┆            ┆           ┆           ┆           ┆           ┆ os/a_cv_i │
│ 19309      ┆ plus       ┆            ┆           ┆           ┆           ┆           ┆ mwrite_im │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ rea…      │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [9]:
path_pattern = "/workspaces/mads-siads-699-winter-2026-capstone/notebooks/data/source_data/pypi_scorecards/*.parquet"
all_files = sorted(glob.glob(path_pattern))
first_five = all_files[:10]
if first_five:
    df = pl.read_parquet(first_five)
    print(f"Loaded {len(first_five)} files.")

Loaded 10 files.

In [10]:
df.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ scorecard_da ┆ repo_name   ┆ repo_commit ┆ scorecard_v ┆ aggregate_s ┆ check_name  ┆ check_score │
│ te           ┆ ---         ┆ ---         ┆ ersion      ┆ core        ┆ ---         ┆ ---         │
│ ---          ┆ str         ┆ str         ┆ ---         ┆ ---         ┆ str         ┆ i64         │
│ date         ┆             ┆             ┆ str         ┆ f64         ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2023-10-30   ┆ github.com/ ┆ 38c84aac41f ┆ v4.13.1-26- ┆ 2.5         ┆ Code-Review ┆ 6           │
│              ┆ keybase/pyk ┆ c03d4d2693f ┆ g478f347e   ┆             ┆             ┆             │
│              ┆ eybasebo…   ┆ b316288d…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ 38c84aac41f ┆ v4.13.1-26- ┆ 2.5         ┆ Pinned-Depe ┆ -1          │
│              ┆ keybase/pyk ┆ c03d4d2693f ┆ g478f347e   ┆             ┆ ndencies    ┆             │
│              ┆ eybasebo…   ┆ b316288d…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ effa7347016 ┆ v4.13.1-26- ┆ 2.5         ┆ Binary-Arti ┆ 10          │
│              ┆ paweltroka/ ┆ 174e460d3c3 ┆ g478f347e   ┆             ┆ facts       ┆             │
│              ┆ signalr-…   ┆ e3f2a9d0…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ 888497987ff ┆ v4.13.1-26- ┆ 3.0         ┆ Dangerous-W ┆ -1          │
│              ┆ kaixuyang/l ┆ e7fecca94f5 ┆ g478f347e   ┆             ┆ orkflow     ┆             │
│              ┆ unarcale…   ┆ 44c03e56…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ 5af5f8bca3b ┆ v4.13.1-26- ┆ 3.0         ┆ CII-Best-Pr ┆ 0           │
│              ┆ jjmontesl/c ┆ 39d18806a05 ┆ g478f347e   ┆             ┆ actices     ┆             │
│              ┆ odenamiz…   ┆ 1fd112ea…   ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [11]:
df['repo_name'].unique()

shape: (20_012,)
Series: 'repo_name' [str]
[
	"github.com/ncoop57/cute_rankin…
	"github.com/tendril-framework/t…
	"github.com/licheng-guo/autobri…
	"github.com/pybitcash/bitcash"
	"github.com/pnx-si/utils-flask-…
	…
	"github.com/mps-youtube/mps-you…
	"github.com/python-trio/trio"
	"github.com/googleapis/proto-pl…
	"github.com/google/casfs"
	"github.com/kalekundert/byoc"
]