In [1]:
path_pattern = "/workspaces/mads-siads-699-winter-2026-capstone/notebooks/data/source_data/initial_dataset/*.parquet"

In [2]:
import polars as pl
import glob

all_files = sorted(glob.glob(path_pattern))
first_five = all_files[:10]
if first_five:
    df_deps = pl.read_parquet(first_five)
    print(f"Loaded {len(first_five)} files.")

Loaded 10 files.

In [3]:
df_deps.shape

(26055035, 8)

In [4]:
df_deps.head(30)

shape: (30, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ SnapshotAt ┆ package_na ┆ package_ve ┆ package_p ┆ dep_name  ┆ dep_versi ┆ MinimumDe ┆ github_re │
│ ---        ┆ me         ┆ rsion      ┆ ublished_ ┆ ---       ┆ on        ┆ pth       ┆ po        │
│ datetime[μ ┆ ---        ┆ ---        ┆ at        ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆ str        ┆ str        ┆ ---       ┆           ┆ str       ┆ i64       ┆ str       │
│            ┆            ┆            ┆ datetime[ ┆           ┆           ┆           ┆           │
│            ┆            ┆            ┆ μs]       ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ certifi   ┆ 2022.12.7 ┆ 3         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆           ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ charset-n ┆ 3.1.0     ┆ 3         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆ ormalizer ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ django-db ┆ 0.1.7     ┆ 1         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆ conn-retr ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆ y         ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ hvac      ┆ 1.1.0     ┆ 1         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆           ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ 2023-04-10 ┆ 12factor-v ┆ 0.1.23     ┆ null      ┆ idna      ┆ 3.4.0     ┆ 3         ┆ jdelic/12 │
│ 21:01:49.2 ┆ ault       ┆            ┆           ┆           ┆           ┆           ┆ factor-va │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ ult       │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2023-04-10 ┆ 2captcha-p ┆ 1.2.0      ┆ null      ┆ urllib3   ┆ 1.26.15   ┆ 2         ┆ 2captcha/ │
│ 21:01:49.2 ┆ ython      ┆            ┆           ┆           ┆           ┆           ┆ 2captcha- │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆ python    │
│ 2023-04-10 ┆ 2ppy       ┆ 0.4.0      ┆ null      ┆ jpype1    ┆ 1.3.0     ┆ 1         ┆ tuprolog/ │
│ 21:01:49.2 ┆            ┆            ┆           ┆           ┆           ┆           ┆ 2ppy      │
│ 19309      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 2023-04-10 ┆ a-cv-imwri ┆ 0.11.0     ┆ null      ┆ certifi   ┆ 2022.12.7 ┆ 2         ┆ hansalema │
│ 21:01:49.2 ┆ te-imread- ┆            ┆           ┆           ┆           ┆           ┆ os/a_cv_i │
│ 19309      ┆ plus       ┆            ┆           ┆           ┆           ┆           ┆ mwrite_im │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ rea…      │
│ 2023-04-10 ┆ a-cv-imwri ┆ 0.11.0     ┆ null      ┆ charset-n ┆ 3.1.0     ┆ 2         ┆ hansalema │
│ 21:01:49.2 ┆ te-imread- ┆            ┆           ┆ ormalizer ┆           ┆           ┆ os/a_cv_i │
│ 19309      ┆ plus       ┆            ┆           ┆           ┆           ┆           ┆ mwrite_im │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ rea…      │
│ 2023-04-10 ┆ a-cv-imwri ┆ 0.11.0     ┆ null      ┆ idna      ┆ 3.4.0     ┆ 2         ┆ hansalema │
│ 21:01:49.2 ┆ te-imread- ┆            ┆           ┆           ┆           ┆           ┆ os/a_cv_i │
│ 19309      ┆ plus       ┆            ┆           ┆           ┆           ┆           ┆ mwrite_im │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ rea…      │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [5]:
path_pattern = "/workspaces/mads-siads-699-winter-2026-capstone/notebooks/data/source_data/pypi_scorecards/*.parquet"
all_files = sorted(glob.glob(path_pattern))
first_five = all_files[:10]
if first_five:
    df_scorecard = pl.read_parquet(first_five)
    print(f"Loaded {len(first_five)} files.")

Loaded 10 files.

In [6]:
df_scorecard.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ scorecard_da ┆ repo_name   ┆ repo_commit ┆ scorecard_v ┆ aggregate_s ┆ check_name  ┆ check_score │
│ te           ┆ ---         ┆ ---         ┆ ersion      ┆ core        ┆ ---         ┆ ---         │
│ ---          ┆ str         ┆ str         ┆ ---         ┆ ---         ┆ str         ┆ i64         │
│ date         ┆             ┆             ┆ str         ┆ f64         ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2023-10-30   ┆ github.com/ ┆ 38c84aac41f ┆ v4.13.1-26- ┆ 2.5         ┆ Code-Review ┆ 6           │
│              ┆ keybase/pyk ┆ c03d4d2693f ┆ g478f347e   ┆             ┆             ┆             │
│              ┆ eybasebo…   ┆ b316288d…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ 38c84aac41f ┆ v4.13.1-26- ┆ 2.5         ┆ Pinned-Depe ┆ -1          │
│              ┆ keybase/pyk ┆ c03d4d2693f ┆ g478f347e   ┆             ┆ ndencies    ┆             │
│              ┆ eybasebo…   ┆ b316288d…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ effa7347016 ┆ v4.13.1-26- ┆ 2.5         ┆ Binary-Arti ┆ 10          │
│              ┆ paweltroka/ ┆ 174e460d3c3 ┆ g478f347e   ┆             ┆ facts       ┆             │
│              ┆ signalr-…   ┆ e3f2a9d0…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ 888497987ff ┆ v4.13.1-26- ┆ 3.0         ┆ Dangerous-W ┆ -1          │
│              ┆ kaixuyang/l ┆ e7fecca94f5 ┆ g478f347e   ┆             ┆ orkflow     ┆             │
│              ┆ unarcale…   ┆ 44c03e56…   ┆             ┆             ┆             ┆             │
│ 2023-10-30   ┆ github.com/ ┆ 5af5f8bca3b ┆ v4.13.1-26- ┆ 3.0         ┆ CII-Best-Pr ┆ 0           │
│              ┆ jjmontesl/c ┆ 39d18806a05 ┆ g478f347e   ┆             ┆ actices     ┆             │
│              ┆ odenamiz…   ┆ 1fd112ea…   ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
df_scorecard['repo_name'].unique()

shape: (20_012,)
Series: 'repo_name' [str]
[
	"github.com/gri38/hyperlink_pre…
	"github.com/iotic-labs/iotics-i…
	"github.com/gamcil/clinker"
	"github.com/jazzband/django-use…
	"github.com/snehankekre/streaml…
	…
	"github.com/thecapypara/riptide…
	"github.com/vladimirs-git/forti…
	"github.com/inveniosoftware/bab…
	"github.com/openworm/pygeppetto"
	"github.com/manuelpepe/pyautobl…
]

In [8]:
df_deps = df_deps.with_columns(
    pl.col("github_repo").str.replace("https://", "").str.replace("github.com/", ""),
    pl.col("package_published_at").cast(pl.Datetime)
)

dtype = df_scorecard.schema.get("scorecard_date")
if dtype is not None and "Date" in str(dtype):
    df_scorecard = df_scorecard.with_columns(
        pl.col("repo_name").str.replace("https://", "").str.replace("github.com/", ""),
        pl.col("scorecard_date").cast(pl.Datetime)
    )
else:
    df_scorecard = df_scorecard.with_columns(
        pl.col("repo_name").str.replace("https://", "").str.replace("github.com/", ""),
        pl.col("scorecard_date").str.to_datetime().cast(pl.Datetime)
    )


df_deps = df_deps.sort("package_published_at")
df_scorecard = df_scorecard.sort("scorecard_date")


df_joined = df_deps.join_asof(
    df_scorecard,
    left_on="package_published_at",
    right_on="scorecard_date",
    by_left="github_repo",
    by_right="repo_name",
    strategy="backward"
)

/tmp/ipykernel_19642/3577651225.py:23: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  df_joined = df_deps.join_asof(

In [16]:
df_joined

shape: (26_055_035, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SnapshotA ┆ package_n ┆ package_v ┆ package_p ┆ … ┆ scorecard ┆ aggregate ┆ check_nam ┆ check_sc │
│ t         ┆ ame       ┆ ersion    ┆ ublished_ ┆   ┆ _version  ┆ _score    ┆ e         ┆ ore      │
│ ---       ┆ ---       ┆ ---       ┆ at        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ datetime[ ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ f64       ┆ str       ┆ i64      │
│ μs]       ┆           ┆           ┆ datetime[ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ μs]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2023-04-1 ┆ 12factor- ┆ 0.1.23    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0 21:01:4 ┆ vault     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9.219309  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-04-1 ┆ 12factor- ┆ 0.1.23    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0 21:01:4 ┆ vault     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9.219309  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-04-1 ┆ 12factor- ┆ 0.1.23    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0 21:01:4 ┆ vault     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9.219309  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-04-1 ┆ 12factor- ┆ 0.1.23    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0 21:01:4 ┆ vault     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9.219309  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-04-1 ┆ 12factor- ┆ 0.1.23    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0 21:01:4 ┆ vault     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9.219309  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2023-10-2 ┆ ccs-digit ┆ 62.3.2    ┆ 2023-10-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3 21:01:3 ┆ almarketp ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ 1.784324  ┆ lace-util ┆           ┆ 11:18:56  ┆   ┆           ┆           ┆           ┆          │
│           ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-10-2 ┆ ccs-digit ┆ 62.3.2    ┆ 2023-10-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3 21:01:3 ┆ almarketp ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ 1.784324  ┆ lace-util ┆           ┆ 11:18:56  ┆   ┆           ┆           ┆           ┆          │
│           ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-10-2 ┆ ccs-digit ┆ 62.3.2    ┆ 2023-10-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3 21:01:3 ┆ almarketp ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ 1.784324  ┆ lace-util ┆           ┆ 11:18:56  ┆   ┆           ┆           ┆           ┆          │
│           ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-10-2 ┆ ccs-digit ┆ 62.3.2    ┆ 2023-10-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3 21:01:3 ┆ almarketp ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ 1.784324  ┆ lace-util ┆           ┆ 11:18:56  ┆   ┆           ┆           ┆           ┆          │
│           ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-10-2 ┆ ecl-data- ┆ 3.1.2     ┆ 2023-10-2 ┆ … ┆ v4.13.0-2 ┆ 5.1       ┆ CII-Best- ┆ 0        │
│ 3 21:01:3 ┆ io        ┆           ┆ 3         ┆   ┆ 9-g49c0ee ┆           ┆ Practices ┆          │
│ 1.784324  ┆           ┆           ┆ 11:42:53  ┆   ┆ d3        ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# below is another method of joining but it's an aggregation and it didn't properly preserve the data

In [9]:
# df_scorecard = df_scorecard.with_columns(
#     pl.col("repo_name").str.replace(r"^github\.com/", "").alias("match_repo")
# )
# df_deps = df_deps.with_columns(
#     pl.col("github_repo").alias("match_repo")
# )

In [10]:
# df_scorecard_collapsed = (
#     df_scorecard
#     .group_by("match_repo")
#     .agg([
#         pl.col("aggregate_score").first(),  # Keep the main score
#         # Optional: Get specific scores as columns
#         pl.col("check_score").filter(pl.col("check_name") == "Code-Review").first().alias("score_code_review"),
#         pl.col("check_score").filter(pl.col("check_name") == "Maintained").first().alias("score_maintained")
#     ])
# )

In [11]:
# df_scorecard_collapsed.head()

In [12]:
# joined_df = df_deps.join(df_scorecard_collapsed, on="match_repo", how="left")

In [13]:
# joined_df